# GitHub Actions CI/CD Pipeline for eBPF Agent
# Place this in: .github/workflows/ci.yaml

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job 1: Lint and format check
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - name: Check Go formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Code is not formatted. Run 'gofmt -s -w .'"
            gofmt -s -l .
            exit 1
          fi

      - name: Check eBPF code formatting
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          find . -name "*.bpf.c" -exec clang-format --dry-run --Werror {} +

  # Job 2: Build and test
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        go-version: ['1.21', '1.22']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            llvm \
            libbpf-dev \
            linux-headers-$(uname -r) \
            bpftool

      - name: Download Go dependencies
        working-directory: ./agent
        run: go mod download

      - name: Build eBPF programs
        working-directory: ./agent
        run: make build-bpf

      - name: Build Go binary
        working-directory: ./agent
        run: make build-go

      - name: Run unit tests
        working-directory: ./agent
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./agent/coverage.out
          flags: unittests

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ebpf-agent-${{ matrix.go-version }}
          path: ./agent/build/

  # Job 3: Integration tests
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev

      - name: Build agent
        working-directory: ./agent
        run: make build

      - name: Run integration tests
        working-directory: ./agent
        run: sudo go test -v -tags=integration ./tests/integration/...

  # Job 4: E2E tests in Kubernetes
  e2e-test:
    name: E2E Tests (Kubernetes)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kind
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: test-cluster

      - name: Build Docker image
        run: |
          docker build -t ebpf-agent:test -f deployment/Dockerfile .

      - name: Load image to kind
        run: kind load docker-image ebpf-agent:test --name test-cluster

      - name: Deploy to kind
        run: |
          kubectl apply -f deployment/kubernetes/namespace.yaml
          kubectl apply -f deployment/kubernetes/daemonset.yaml

      - name: Wait for pods
        run: |
          kubectl wait --for=condition=ready pod \
            -l app=ebpf-agent -n ebpf-system --timeout=300s

      - name: Run E2E tests
        run: |
          kubectl run test-pod --image=busybox --restart=Never -- sleep 60
          # Verify agent captured the pod creation
          kubectl logs -n ebpf-system -l app=ebpf-agent --tail=100

      - name: Collect logs on failure
        if: failure()
        run: |
          kubectl get pods -A
          kubectl logs -n ebpf-system -l app=ebpf-agent --tail=500

  # Job 5: Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'

      - name: Build Docker image
        run: docker build -t ebpf-agent:scan -f deployment/Dockerfile .

      - name: Run Trivy (container image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ebpf-agent:scan'
          severity: 'CRITICAL,HIGH'

  # Job 6: Build and push container image
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build, integration-test, security-scan]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}

  # Job 7: Deploy to staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: docker-build-push
    if: github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://staging.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_STAGING }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to staging
        run: |
          kubectl set image daemonset/ebpf-agent \
            ebpf-agent=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main \
            -n ebpf-system

      - name: Wait for rollout
        run: |
          kubectl rollout status daemonset/ebpf-agent -n ebpf-system --timeout=5m

  # Job 8: Deploy to production (manual approval)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker-build-push
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: production
      url: https://production.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_PRODUCTION }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to production
        run: |
          kubectl set image daemonset/ebpf-agent \
            ebpf-agent=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            -n ebpf-system

      - name: Wait for rollout
        run: |
          kubectl rollout status daemonset/ebpf-agent -n ebpf-system --timeout=10m

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

/*
 * CI/CD Pipeline Features:
 *
 * 1. Comprehensive Testing:
 *    - Unit tests with race detection
 *    - Integration tests
 *    - E2E tests in real Kubernetes cluster
 *    - Code coverage tracking
 *
 * 2. Security:
 *    - Trivy vulnerability scanning
 *    - Docker image scanning
 *    - Dependency auditing
 *
 * 3. Multi-Architecture:
 *    - Builds for amd64 and arm64
 *    - Uses Docker Buildx
 *    - Layer caching for speed
 *
 * 4. Progressive Deployment:
 *    - Staging environment (automatic on main)
 *    - Production environment (manual approval on tags)
 *    - Rollout monitoring
 *
 * 5. Quality Gates:
 *    - Lint must pass
 *    - Tests must pass
 *    - Security scan must pass
 *    - Only then deployment proceeds
 *
 * Repository Secrets Needed:
 * - GITHUB_TOKEN (automatic)
 * - KUBECONFIG_STAGING (base64 encoded)
 * - KUBECONFIG_PRODUCTION (base64 encoded)
 *
 * Similar to:
 * - Cilium's CI pipeline
 * - Tetragon's release process
 * - Falco's build system
 */
